# Generated by Django 4.2.16 on 2024-09-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rutas', '0001_initial'),
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=3)),
                ('FechaInicio', models.DateTimeField()),
                ('FechaFIn', models.DateTimeField()),
                ('Monto', models.CharField(max_length=20)),
                ('Grado', models.CharField(max_length=10)),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Estudiante.estudiante')),
                ('idRutas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Rutas.rutas')),
            ],
        ),
    ]
