# Generated by Django 4.2.16 on 2024-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detalles_De_Ruta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_de_ruta',
            name='Descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
