# Generated by Django 4.2.16 on 2024-09-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=7)),
                ('NumVehicle', models.CharField(max_length=5)),
                ('Descripcion', models.TextField()),
                ('capacidad', models.CharField(max_length=20)),
            ],
        ),
    ]
