# Generated by Django 4.2.16 on 2024-09-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=3)),
                ('Monto', models.CharField(max_length=20)),
                ('Fecha', models.DateTimeField()),
                ('idPagos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Pagos.pagos')),
            ],
        ),
    ]
