# Generated by Django 4.2.16 on 2024-09-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='idPagos',
            new_name='idContratos',
        ),
    ]
