# Generated by Django 4.2.16 on 2024-09-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_rename_idpagos_pagos_idcontratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='idContratos',
        ),
    ]
