# Generated by Django 4.2.16 on 2024-09-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contrato', '0001_initial'),
        ('Pagos', '0003_remove_pagos_idcontratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='idContratos',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.RESTRICT, to='Contrato.contratos'),
            preserve_default=False,
        ),
    ]
