# Generated by Django 4.2.16 on 2024-09-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0009_alter_pagos_idcontratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='idContratos',
        ),
    ]
